name: py-docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: py
      - name: Check Python version
        run: python --version
      - name: Check uv version
        run: uv --version
      - name: Install dependencies
        working-directory: ./py
        run: uv sync --locked --all-extras --dev
      - name: Sphinx build
        uses: ammaraskar/sphinx-action@master
        with:
            docs-folder: "py/doc/"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: py/doc/build/html
          force_orphan: true